<?php if ($_products = $this->getProductCollection()): ?>
    <h2 class="subtitle"><?php echo $this->__('Featured Product') ?></h2>
    <ul class="feature-products-grid">
        <?php
        foreach ($_products as $_product): ?>
            <li class="item">
                <?php if ($this->displayImage()): ?>
                    <a href="<?php echo $_product->getProductUrl() ?>"
                       title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"
                       class="product-image"><img
                            src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135) ?>"
                            width="135" height="135"
                            alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>"/></a>
                <?php endif; ?>
                <?php if ($this->displayPrice()): ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                <?php endif; ?>
                <div class="actions">
                    <?php if ($_product->isSaleable()): ?>
                        <button type="button"
                                title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>"
                                class="button btn-cart"
                                onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                            <span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                </div>
            </li>
        <?php endforeach; ?>
    </ul>
    <div style="clear: both"></div>
<?php endif; ?>
